#!/bin/zsh
TFMUDSDIR=${TFMUDSDIR:-./muds}
TFLIBDIR=${TFLIBDIR:-../../lib}
TFMAIN=$TFLIBDIR/mainlib.tt
LOGFILE="logs/log.txt"
CHATFILE="logs/chat.txt"
MAPFILE="logs/map.txt"
STATFILE="logs/status.txt"
MULTIFILE="logs/other.txt"
MAINTT="main.tt"

if [[ -z "$1" || ! -d $TFMUDSDIR/$1 ]]
then
  echo "Usage: $(basename $0) <name>, where <name> is one of:"
  cd $TFMUDSDIR
  ls | sed -e "s/blank//" -e "s/past//" -e "s/lib//" | xargs echo
  cd -
else
  # name of tmux session
  export SESSION="$1"
   
  # if session already running, attach it.
  tmux has-session -t $SESSION 2> /dev/null
  if [ $? -eq 0 ]; then
    echo "Session $SESSION already exists. Attaching."
    sleep 1
    tmux attach -t $SESSION
  else
    # else create it, and detach it to work on it a bit
    tmux new-session -d -s $SESSION
    # populate the session using corresponding script
    echo populating session for $TFMUDSDIR/$SESSION
     
    # act on shell first
    cd $TFMUDSDIR/$SESSION
     
    # setup window and start tintin
    # auto-detect user's actual shell and use the same in second tmux window
    tmux new-window    -t $SESSION:1 -k -n "tintin" "$SHELL"
    tmux send-keys     -t $SESSION:1 "tintin -G -e \"#var libdir $TFLIBDIR\" -e \"#var tinframe $TFMAIN\" -t main $MAINTT && tmux kill-session" Enter
    tmux new-window    -t $SESSION:2 -k -n "vim"
    tmux select-window -t $SESSION:1
    
    # setup panes and start chat, log, map and status streams
    # first split: left 1.1 | right 1.2 -- secondary column has smaller width than tintin window
    tmux split-window -t $SESSION:1   -h -l 60 "tail -Fs1 $LOGFILE"
    # split left between up 1.3 / down 1.1 -- other char's pane should have same width as tintin pane
    tmux split-window -t $SESSION:1.1 -b -v "less +F -R $MULTIFILE"
    tmux resize-pane  -t $SESSION:1.3 -y 8
    # split right between up 1.2 / down 1.4 -- map on secondary column, fixed width for map
    tmux split-window -t $SESSION:1.2 -v -l 22 "tail -Fs0.5 $MAPFILE"
    # split right between up 1.2 / down 1.5 -- chat on secondary column
    tmux split-window -t $SESSION:1.2 -v "tail -Fs0.5 $CHATFILE"
    # split right between up 1.6 / down 1.2 -- last split *if* status file is used
    if [[ -f $STATFILE ]]; then
      tmux split-window -t $SESSION:1.2 -b -v "tail -Fs1 $STATFILE"
      tmux resize-pane  -t $SESSION:1.6 -y 8
    fi
    # select main pane
    tmux select-pane  -t $SESSION:1.1
        
    # re-attach session
    exec tmux attach -t $SESSION
  fi
fi
#------------------------
# CopyLeft by dalker
# create date: 2016-04-15
# modif  date: 2016-05-29
