#!/bin/bash
TFMUDSDIR=${TFMUDSDIR:-./muds}
TFLIBDIR=${TFLIBDIR:-../../lib}
TFMAIN=$TFLIBDIR/mainlib.tt
PANEDIR="panes/"
LOGFILE="${PANEDIR}log.txt"
CHATFILE="${PANEDIR}chat.txt"
MAPFILE="${PANEDIR}map.txt"
STATFILE="${PANEDIR}stat.txt"
MAINTT="main.tt"

if [[ -z "$1" || ! -d $TFMUDSDIR/$1 ]]
then
  echo "Usage: $(basename $0) <name>, where <name> is one of:"
  cd $TFMUDSDIR
  ls | sed -e "s/blank//" -e "s/past//" -e "s/lib//" | xargs echo
else
  # name of tmux session
  export SESSION="$1"
   
  # if session already running, attach it.
  tmux has-session -t $SESSION 2> /dev/null
  if [ $? -eq 0 ]; then
    echo "Session $SESSION already exists. Attaching."
    sleep 1
    tmux attach -t $SESSION
  else
    # else create it, and detach it to work on it a bit
    tmux new-session -d -s $SESSION
    # populate the session using corresponding script
    echo populating session for $TFMUDSDIR/$SESSION
     
    # act on shell first
    cd $TFMUDSDIR/$SESSION
    mkdir -p $PANEDIR
     
    # setup window 1
    # auto-detect user's actual shell and use the same in second tmux window
    tmux new-window    -t $SESSION:1 -k -n "tintin" "$SHELL"
    tmux send-keys     -t $SESSION:1 "tintin -G -e \"#var libdir $TFLIBDIR\" -e \"#var tinframe $TFMAIN\" -t main $MAINTT && tmux kill-session" Enter
    tmux select-window -t $SESSION:1
    # split left between up 1.2 / down 1.1
    tmux split-window -t $SESSION:1.1 -b -v "tail -Fs1 $CHATFILE"
    tmux resize-pane  -t $SESSION:1.2 -y 8
    
    # setup window 2
    tmux new-window   -t $SESSION:2 -k -n "logs" "tail -Fs1 $LOGFILE"
    tmux select-window -t $SESSION:2
    # split between up 2.1 / down 2.2
    if [[ -f $STATFILE ]]; then
      tmux split-window -t $SESSION:2.1 -b -l 22 "tail -Fs1 $STATFILE"
    fi
    # split between left 2.1 / right 2.3
    tmux split-window -t $SESSION:2.1 -h -l 60 "tail -Fs0.5 $MAPFILE"

    # setup window 3
    tmux new-window    -t $SESSION:3 -k -n "$(basename $SHELL)"

    # select main pane
    tmux select-window -t $SESSION:1
    tmux select-pane  -t $SESSION:1.1
        
    # re-attach session
    exec tmux attach -t $SESSION
  fi
fi
#------------------------
# CopyLeft by dalker
# create date: 2015-07-26
# modif  date: 2016-06-05
