#!/bin/bash

# location of TinFrame muds and lib dirs as well as main lib and mud files
export TFMUDSDIR=${TFMUDSDIR:-./muds}
export  TFLIBDIR=${TFLIBDIR:-../../lib}
export    TFMAIN=$TFLIBDIR/mainlib.tt
export    MAINTT="main.tt"

# location of panes files and their names
export  PANEDIR="panes/"
export  LOGFILE="log.txt"
export CHATFILE="chat.txt"
export  MAPFILE="map.txt"
export STATFILE="stat.txt"
export  ALTFILE="alt.txt"
export  BLTFILE="blt.txt"

#------------------------
# CopyLeft by dalker
# create date: 2016-07-07
# modif  date: 2016-07-07
